version: '3.8'

services:
  backend:
    build: .
    image: max96811/romstore-backend:latest
    restart: unless-stopped
    volumes:
      - ${DATA_PATH:-./data}:/usr/src/app/data
      - ${EMULATION_PATH:-/mnt/emulation}:/emulation
    environment:
      - PORT=3000
    networks:
      - app-network
  frontend:
    build: ./frontend
    image: max96811/romstore-frontend:latest
    restart: unless-stopped
    ports:
      - "1567:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
